// const orgData = [
//   {
//     Batch: 10,
//     Group: "Core",
//     Resource: "Dina Michaely",
//     role: "Analyst",
//   },
//   {
//     Batch: 10,
//     Group: "Core",
//     Resource: "Yuval Belenky",
//     role: "Analyst",
//   },
//   {
//     Batch: 11,
//     Group: "Core",
//     Resource: "Deeshma Aiyappa Chottangada",
//     role: "Analyst",
//   },
//   {
//     Batch: 11,
//     Group: "Core",
//     Resource: "Shilpa Govindaraju",
//     role: "Analyst",
//   },
//   {
//     Batch: 11,
//     Group: "Core",
//     Resource: "Nikhil Rajesh Deshmukh",
//     role: "Analyst",
//   },
//   {
//     Batch: 11,
//     Group: "Core",
//     Resource: "Anand Menankandy Kombra",
//     role: "Analyst",
//   },
//   {
//     Batch: 11,
//     Group: "Core",
//     Resource: "Damini Jogi",
//     role: "Analyst",
//   },
//   {
//     Batch: 11,
//     Group: "Core",
//     Resource: "Anupama Ravikumar",
//     role: "Analyst",
//   },
//   {
//     Batch: 11,
//     Group: "Core",
//     Resource: "Sidharth Purushothaman Edayath",
//     role: "Analyst",
//   },
//   {
//     Batch: 11,
//     Group: "Core",
//     Resource: "Ayushi Gupta",
//     role: "Analyst",
//   },
//   {
//     Batch: 11,
//     Group: "Core",
//     Resource: "Anil Kodiganti",
//     role: "Analyst",
//   },
//   {
//     Batch: 11,
//     Group: "Core",
//     Resource: "Megha Singhal",
//     role: "Analyst",
//   },
//   {
//     Batch: 12,
//     Group: "Core",
//     Resource: "Yellampalli Madhura",
//     role: "Analyst",
//   },
//   {
//     Batch: 12,
//     Group: "Core",
//     Resource: "Leo Louis Kooliyadan",
//     role: "Analyst",
//   },
//   {
//     Batch: 12,
//     Group: "Core",
//     Resource: "Chittuluri Mahesh",
//     role: "Analyst",
//   },
//   {
//     Batch: 12,
//     Group: "Core",
//     Resource: "Nakatte Karthik Prakash Shetty",
//     role: "Analyst",
//   },
//   {
//     Batch: 12,
//     Group: "Core",
//     Resource: "Nasreen Firdous",
//     role: "Analyst",
//   },
//   { Batch: 12, Group: "Core", Resource: "Amit Magoz", role: "Analyst" },
//   {
//     Batch: 13,
//     Group: "Core",
//     Resource: "Hiteshwar Dutt",
//     role: "Analyst",
//   },
//   {
//     Batch: 13,
//     Group: "Core",
//     Resource: "Shubham Agarwal",
//     role: "Analyst",
//   },
//   {
//     Batch: 13,
//     Group: "Core",
//     Resource: "Rajat Lamba",
//     role: "Analyst",
//   },
//   {
//     Batch: 13,
//     Group: "Core",
//     Resource: "Poulami Saha",
//     role: "Analyst",
//   },
//   {
//     Batch: 13,
//     Group: "Core",
//     Resource: "Srijani Saha",
//     role: "Analyst",
//   },
//   {
//     Batch: 13,
//     Group: "Core",
//     Resource: "Swati Suman",
//     role: "Analyst",
//   },
//   {
//     Batch: 13,
//     Group: "Core",
//     Resource: "Biduduri Himaja",
//     role: "Analyst",
//   },
//   {
//     Batch: 13,
//     Group: "Core",
//     Resource: "Pawan Kumar",
//     role: "Analyst",
//   },
//   {
//     Batch: 13,
//     Group: "Core",
//     Resource: "Jagriti Lnu",
//     role: "Analyst",
//   },
//   {
//     Batch: 13,
//     Group: "Core",
//     Resource: "Priya Sharma",
//     role: "Analyst",
//   },
//   {
//     Batch: 13,
//     Group: "Core",
//     Resource: "Akash Kumar Ojha",
//     role: "Analyst",
//   },
//   {
//     Batch: 14,
//     Group: "Core",
//     Resource: "Ayanabha Karmakar",
//     role: "Analyst",
//   },
//   {
//     Batch: 14,
//     Group: "Core",
//     Resource: "Navya Shukla",
//     role: "Analyst",
//   },
//   {
//     Batch: 14,
//     Group: "Core",
//     Resource: "Subham Agarwal",
//     role: "Analyst",
//   },
//   {
//     Batch: 14,
//     Group: "Core",
//     Resource: "Tamar Hochberg",
//     role: "Analyst",
//   },
//   {
//     Batch: 15,
//     Group: "Core",
//     Resource: "Usman Fuzail",
//     role: "Analyst",
//   },
//   {
//     Batch: 15,
//     Group: "Core",
//     Resource: "Ashish D'Souza",
//     role: "Analyst",
//   },
//   {
//     Batch: 15,
//     Group: "Core",
//     Resource: "Priyanka Teresa Lucas",
//     role: "Analyst",
//   },
//   { Batch: 15, Group: "Core", Resource: "Lavish Siddiqui" },
//   {
//     Batch: 15,
//     Group: "Core",
//     Resource: "Mohamad Azaruddin Mohiddin",
//     role: "Analyst",
//   },
//   {
//     Batch: 15,
//     Group: "Core",
//     Resource: "Omkar Anil Somawar",
//     role: "Analyst",
//   },
//   {
//     Batch: 15,
//     Group: "Core",
//     Resource: "Smruti Swarupa Panda",
//     role: "Analyst",
//   },
//   {
//     Batch: 16,
//     Group: "Core",
//     Resource: "Mugunth Subash Murugesan",
//     role: "Analyst",
//   },
//   {
//     Batch: 16,
//     Group: "Core",
//     Resource: "Shefali Mittal",
//     role: "Analyst",
//   },
//   {
//     Batch: 16,
//     Group: "Core",
//     Resource: "Nikhil Suri",
//     role: "Analyst",
//   },
//   {
//     Batch: 16,
//     Group: "Core",
//     Resource: "Bhavya Gupta",
//     role: "Analyst",
//   },
//   {
//     Batch: 16,
//     Group: "Core",
//     Resource: "Mitali Gupta",
//     role: "Analyst",
//   },
//   { Batch: 16, Group: "Core", Resource: "Naincy Lnu", role: "Analyst" },
//   {
//     Batch: 16,
//     Group: "Core",
//     Resource: "Devanshu Bhalla",
//     role: "Analyst",
//   },
//   {
//     Batch: 16,
//     Group: "Core",
//     Resource: "Piyush Singh",
//     role: "Analyst",
//   },
//   {
//     Batch: 16,
//     Group: "Core",
//     Resource: "Tanya Aggarwal",
//     role: "Analyst",
//   },
//   {
//     Batch: 16,
//     Group: "Core",
//     Resource: "Vivek Singh Patel",
//     role: "Analyst",
//   },
//   {
//     Batch: 16,
//     Group: "Core",
//     Resource: "Manaswi Sanwal",
//     role: "Analyst",
//   },
//   {
//     Batch: 16,
//     Group: "Core",
//     Resource: "Anshika Tripathi",
//     role: "Analyst",
//   },
//   {
//     Batch: 16,
//     Group: "Core",
//     Resource: "Roshni Shrestha",
//     role: "Analyst",
//   },
//   {
//     Batch: 16,
//     Group: "Core",
//     Resource: "Elad Seidler",
//     role: "Analyst",
//   },
//   {
//     Batch: 16,
//     Group: "Core",
//     Resource: "Dorin Golan",
//     role: "Analyst",
//   },
//   { Batch: 16, Group: "Core", Resource: "Matan Edri", role: "Analyst" },
//   {
//     Batch: 17,
//     Group: "Core",
//     Resource: "Martin James",
//     role: "Analyst",
//   },
//   {
//     Batch: 17,
//     Group: "Core",
//     Resource: "Nandini Sarda",
//     role: "Analyst",
//   },
//   {
//     Batch: 17,
//     Group: "Core",
//     Resource: "Allu Chandana",
//     role: "Analyst",
//   },
//   {
//     Batch: 17,
//     Group: "Core",
//     Resource: "Lalitha Lakshmi Narayanayyar Sivaramakrishnan",
//     role: "Analyst",
//   },
//   {
//     Batch: 17,
//     Group: "Core",
//     Resource: "Chandhana Rodda Nagaraj",
//     role: "Analyst",
//   },
//   {
//     Batch: 17,
//     Group: "Core",
//     Resource: "Neha Rajeevan",
//     role: "Analyst",
//   },
//   {
//     Batch: 17,
//     Group: "Core",
//     Resource: "Nerella Hema Bindu",
//     role: "Analyst",
//   },
//   {
//     Batch: 17,
//     Group: "Core",
//     Resource: "Angad Singh",
//     role: "Analyst",
//   },
//   {
//     Batch: 17,
//     Group: "Core",
//     Resource: "Noshi Babu Sandhya",
//     role: "Analyst",
//   },
//   { Batch: 17, Group: "Core", Resource: "Arad Drori", role: "Analyst" },
//   {
//     Batch: 17,
//     Group: "Core",
//     Resource: "Rishabh Yadav",
//     role: "Analyst",
//   },
//   {
//     Batch: 17,
//     Group: "Core",
//     Resource: "Sumit  Rajawat",
//     role: "Analyst",
//   },
//   {
//     Batch: 17,
//     Group: "Core",
//     Resource: "Amitoj Singh Chhabra",
//     role: "Analyst",
//   },
//   {
//     Batch: 17,
//     Group: "Core",
//     Resource: "Bhavya Ranka",
//     role: "Analyst",
//   },
//   {
//     Batch: 18,
//     Group: "Core",
//     Resource: "Mahesh Garla",
//     role: "Analyst",
//   },
//   {
//     Batch: 18,
//     Group: "Core",
//     Resource: "Vrishab Kumar Boggaram Suresh",
//     role: "Analyst",
//   },
//   {
//     Batch: 18,
//     Group: "Core",
//     Resource: "Sai Krishna Anasuri",
//     role: "Analyst",
//   },
//   {
//     Batch: 18,
//     Group: "Core",
//     Resource: "Sameer Gupta",
//     role: "Analyst",
//   },
//   { Batch: 18, Group: "Core", Resource: "Riya LNU", role: "Analyst" },
//   {
//     Batch: 18,
//     Group: "Core",
//     Resource: "Isabel Rose Prinson",
//     role: "Analyst",
//   },
//   {
//     Batch: 18,
//     Group: "Core",
//     Resource: "Parina Ahluwalia",
//     role: "Analyst",
//   },
//   { Batch: 18, Group: "Core", Resource: "Muskan LNU", role: "Analyst" },
//   {
//     Batch: 18,
//     Group: "Core",
//     Resource: "Ishdeep Singh Bharaj",
//     role: "Analyst",
//   },
//   { Batch: 18, Group: "Core", Resource: "Aniket Dey", role: "Analyst" },
//   {
//     Batch: 18,
//     Group: "Core",
//     Resource: "Sweta Kumari",
//     role: "Analyst",
//   },
//   {
//     Batch: 18,
//     Group: "Core",
//     Resource: "Faizan Aman",
//     role: "Analyst",
//   },
//   {
//     Batch: 18,
//     Group: "Core",
//     Resource: "Gurudutt Pal",
//     role: "Analyst",
//   },
//   {
//     Batch: 18,
//     Group: "Core",
//     Resource: "Chaturvedi  Anmol",
//     role: "Analyst",
//   },
//   {
//     Batch: 18,
//     Group: "Core",
//     Resource: "Jassal Chhavi",
//     role: "Analyst",
//   },
//   {
//     Batch: 18,
//     Group: "Core",
//     Resource: "Divya Nanjundappa",
//     role: "Analyst",
//   },
//   {
//     Batch: 19,
//     Group: "Core",
//     Resource: "Hezron Parado",
//     role: "Analyst",
//   },
//   {
//     Batch: 19,
//     Group: "Core",
//     Resource: "Meenakshi Vailapilly Jagadeep",
//     role: "Analyst",
//   },
//   {
//     Batch: 19,
//     Group: "Core",
//     Resource: "Madhur Grover",
//     role: "Analyst",
//   },
//   {
//     Batch: 19,
//     Group: "Core",
//     Resource: "Alicia Arogya Swamy",
//     role: "Analyst",
//   },
//   {
//     Batch: 20,
//     Group: "Core",
//     Resource: "Jayasheela J R",
//     role: "Analyst",
//   },
//   {
//     Batch: 20,
//     Group: "Core",
//     Resource: "Maahi Agarwal",
//     role: "Analyst",
//   },
//   {
//     Batch: 20,
//     Group: "Core",
//     Resource: "Sarthak Mohanty",
//     role: "Analyst",
//   },
//   {
//     Batch: 20,
//     Group: "Core",
//     Resource: "Nandini Prakash",
//     role: "Analyst",
//   },
//   {
//     Batch: 20,
//     Group: "Core",
//     Resource: "Divyakshi Gupta",
//     role: "Analyst",
//   },
//   {
//     Batch: 20,
//     Group: "Core",
//     Resource: "Erikhomba Meetei Huidrom",
//     role: "Analyst",
//   },
//   { Batch: 21, Group: "Core", Resource: "Mansi Sood", role: "Analyst" },
//   {
//     Batch: 21,
//     Group: "Core",
//     Resource: "Aisiri Ravi",
//     role: "Analyst",
//   },
//   {
//     Batch: 21,
//     Group: "Core",
//     Resource: "Kathroju Hima Bindu",
//     role: "Analyst",
//   },
//   {
//     Batch: 21,
//     Group: "Core",
//     Resource: "Reshma Bhanu",
//     role: "Analyst",
//   },
//   {
//     Batch: 21,
//     Group: "Core",
//     Resource: "Bhavana Rajendra Joge",
//     role: "Analyst",
//   },
//   {
//     Batch: 21,
//     Group: "Core",
//     Resource: "Pranavu Prasannan",
//     role: "Analyst",
//   },
//   {
//     Batch: 21,
//     Group: "Core",
//     Resource: "Prem Kumar Venkatesh",
//     role: "Analyst",
//   },
//   {
//     Batch: 21,
//     Group: "Core",
//     Resource: "Supriya Prakash",
//     role: "Analyst",
//   },
//   {
//     Batch: 21,
//     Group: "Core",
//     Resource: "Revathi Jagadish",
//     role: "Analyst",
//   },
//   {
//     Batch: 21,
//     Group: "Core",
//     Resource: "Rashid Nadukkandiyil",
//     role: "Analyst",
//   },
//   {
//     Batch: 21,
//     Group: "Core",
//     Resource: "Shayamala Rohith",
//     role: "Analyst",
//   },
//   {
//     Batch: 21,
//     Group: "Core",
//     Resource: "Gayatri Kumar",
//     role: "Analyst",
//   },
//   {
//     Batch: 21,
//     Group: "Core",
//     Resource: "Sreya Sudhakaran",
//     role: "Analyst",
//   },
//   {
//     Batch: 21,
//     Group: "Core",
//     Resource: "Sharannya Ghosh",
//     role: "Analyst",
//   },
//   {
//     Batch: 21,
//     Group: "Core",
//     Resource: "Kiran Kanika Baskar",
//     role: "Analyst",
//   },
//   {
//     Batch: 21,
//     Group: "Core",
//     Resource: "Priyaanka Nagendra Dixit",
//     role: "Analyst",
//   },
//   {
//     Batch: 21,
//     Group: "Core",
//     Resource: "Keerthi Kennedy",
//     role: "Analyst",
//   },
//   {
//     Batch: 22,
//     Group: "Core",
//     Resource: "Murugan Rajitha",
//     role: "Analyst",
//   },
//   {
//     Batch: 22,
//     Group: "Core",
//     Resource: "Thanusha Janjanam",
//     role: "Analyst",
//   },
//   {
//     Batch: 22,
//     Group: "Core",
//     Resource: "Mahima Purohit",
//     role: "Analyst",
//   },
//   {
//     Batch: 22,
//     Group: "Core",
//     Resource: "Jeedigunta Kanaka Gowri Mahalakshmi",
//     role: "Analyst",
//   },
//   {
//     Batch: 22,
//     Group: "Core",
//     Resource: "Priyanshu Pareek",
//     role: "Analyst",
//   },
//   {
//     Batch: 22,
//     Group: "Core",
//     Resource: "Shiva Thalaiyur Venkatanathan",
//     role: "Analyst",
//   },
//   { Batch: 22, Group: "Core", Resource: "Annu Nisal", role: "Analyst" },
//   {
//     Batch: 22,
//     Group: "Core",
//     Resource: "PRITAM PARIDA",
//     role: "Analyst",
//   },
//   {
//     Batch: 22,
//     Group: "Core",
//     Resource: "Pragya Gupta",
//     role: "Analyst",
//   },
//   {
//     Batch: 22,
//     Group: "Core",
//     Resource: "Eitan Stattia",
//     role: "Analyst",
//   },
//   {
//     Batch: 22,
//     Group: "Core",
//     Resource: "Ritesh Sharma",
//     role: "Analyst",
//   },
//   {
//     Batch: 22,
//     Group: "Core",
//     Resource: "Sharon Sitton Soffer",
//     role: "Analyst",
//   },
//   { Batch: 23, Group: "Core", Resource: "Neha Mittal", role: "Analyst" },
// ];

const TeamMapping = [
  {
    Batch: "1 - S",
    "L1 Analyst - ECM": "Ayushi Gupta",
    "L1 Analyst": "Ayushi Gupta",
    "L1 QC - ECM": "Anuloma Tripathy",
    "L1 QC": "Anuloma Tripathy",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Wendy Arroyo",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Sampling - Location Based",
    Location: "Gurgaon",
    "Sampling Date": "9/18/2023",
  },
  {
    Batch: "1",
    "L1 Analyst - ECM": "Damini Jogi",
    "L1 Analyst": "Damini Jogi",
    "L1 QC - ECM": "Hiteshwar Dutt",
    "L1 QC": "Hiteshwar Dutt",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Kiran Goli",
    "L2 QC": "Kassidy Collins",
    "L2 Team Lead": "Michael Herpin",
    "Case Type": "Location Based",
    Location: "Hyderabad",
    "Sampling Date": "",
  },
  {
    Batch: "1",
    "L1 Analyst - ECM": "Kodiganti Anil",
    "L1 Analyst": "Anil Kodiganti",
    "L1 QC - ECM": "Hiteshwar Dutt",
    "L1 QC": "Hiteshwar Dutt",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Kiran Goli",
    "L2 QC": "Kassidy Collins",
    "L2 Team Lead": "Michael Herpin",
    "Case Type": "Location Based - Very High",
    Location: "Hyderabad",
    "Sampling Date": "",
  },
  {
    Batch: "1",
    "L1 Analyst - ECM": "Megha Singhal",
    "L1 Analyst": "Megha Singhal",
    "L1 QC - ECM": "Hafiza Ansari",
    "L1 QC": "Hafiza Ansari",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Kiran Goli",
    "L2 QC": "Kassidy Collins",
    "L2 Team Lead": "Michael Herpin",
    "Case Type": "Location Based",
    Location: "Hyderabad",
    "Sampling Date": "",
  },
  {
    Batch: "2",
    "L1 Analyst - ECM": "Ayanabha Karmakar",
    "L1 Analyst": "Ayanabha Karmakar",
    "L1 QC - ECM": "Rajat Lamba",
    "L1 QC": "Rajat Lamba",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Wendy Arroyo",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Gurgaon",
    "Sampling Date": "",
  },
  {
    Batch: "2",
    "L1 Analyst - ECM": "Bidudiri Himaja",
    "L1 Analyst": "Bidudiri Himaja",
    "L1 QC - ECM": "Hiteshwar Dutt",
    "L1 QC": "Hiteshwar Dutt",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Kiran Goli",
    "L2 QC": "Kassidy Collins",
    "L2 Team Lead": "Michael Herpin",
    "Case Type": "Location Based",
    Location: "Hyderabad",
    "Sampling Date": "",
  },
  {
    Batch: "2",
    "L1 Analyst - ECM": "Mahesh Garla",
    "L1 Analyst": "Mahesh Garla",
    "L1 QC - ECM": "Ajay Minocha",
    "L1 QC": "Ajay Minocha",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Reuven Salter",
    "L2 Team Lead": "Sai Goli",
    "Case Type": "Location Based",
    Location: "Hyderabad",
    "Sampling Date": "",
  },
  {
    Batch: "2",
    "L1 Analyst - ECM": "Mansi Sood",
    "L1 Analyst": "Mansi Sood",
    "L1 QC - ECM": "Ajay Minocha",
    "L1 QC": "Ajay Minocha",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Reuven Salter",
    "L2 Team Lead": "Sai Goli",
    "Case Type": "Location Based",
    Location: "Gurgaon",
    "Sampling Date": "",
  },
  {
    Batch: "2",
    "L1 Analyst - ECM": "Mohamad Mohiddin",
    "L1 Analyst": "Mohamad Azaruddin Mohiddin",
    "L1 QC - ECM": "Mohammed Raza",
    "L1 QC": "Mohammed Kazim Raza",
    "L1 Team Lead - ECM": "Valloor Harisankar",
    "L1 Team Lead": "Valloor Harisankar",
    "L2 QC": "Chantell Redish",
    "L2 Team Lead": "Katie Fogle",
    "Case Type": "Location Based",
    Location: "Bangalore",
    "Sampling Date": "",
  },
  {
    Batch: "2",
    "L1 Analyst - ECM": "Murugan Rajitha",
    "L1 Analyst": "Murugan Rajitha",
    "L1 QC - ECM": "Ajay Minocha",
    "L1 QC": "Ajay Minocha",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Reuven Salter",
    "L2 Team Lead": "Sai Goli",
    "Case Type": "Location Based",
    Location: "Hyderabad",
    "Sampling Date": "",
  },
  {
    Batch: "2",
    "L1 Analyst - ECM": "Navya Shukla",
    "L1 Analyst": "Navya Shukla",
    "L1 QC - ECM": "Hiteshwar Dutt",
    "L1 QC": "Hiteshwar Dutt",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Kiran Goli",
    "L2 QC": "Michael Herpin",
    "L2 Team Lead": "Michael Herpin",
    "Case Type": "Location Based",
    Location: "Hyderabad",
    "Sampling Date": "",
  },
  {
    Batch: "2",
    "L1 Analyst - ECM": "Nikhil Suri",
    "L1 Analyst": "Nikhil Suri",
    "L1 QC - ECM": "Anuloma Tripathy",
    "L1 QC": "Anuloma Tripathy",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Wendy Arroyo",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Gurgaon",
    "Sampling Date": "",
  },
  {
    Batch: "2",
    "L1 Analyst - ECM": "Omkar Somawar",
    "L1 Analyst": "Omkar Anil Somawar",
    "L1 QC - ECM": "Reuven Salter",
    "L1 QC": "Reuven Salter",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Kiran Goli",
    "L2 QC": "Michael Herpin",
    "L2 Team Lead": "Michael Herpin",
    "Case Type": "Location Based",
    Location: "Hyderabad",
    "Sampling Date": "",
  },
  {
    Batch: "2",
    "L1 Analyst - ECM": "Pawan Kumar",
    "L1 Analyst": "Pawan Kumar",
    "L1 QC - ECM": "Ajay Minocha",
    "L1 QC": "Ajay Minocha",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Wendy Arroyo",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Gurgaon",
    "Sampling Date": "",
  },
  {
    Batch: "2",
    "L1 Analyst - ECM": "Poulami Saha",
    "L1 Analyst": "Poulami Saha",
    "L1 QC - ECM": "Rajat Lamba",
    "L1 QC": "Rajat Lamba",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Wendy Arroyo",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Gurgaon",
    "Sampling Date": "",
  },
  {
    Batch: "2",
    "L1 Analyst - ECM": "Shubham Agarwal",
    "L1 Analyst": "Shubham Agarwal",
    "L1 QC - ECM": "Ajay Minocha",
    "L1 QC": "Ajay Minocha",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Wendy Arroyo",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Gurgaon",
    "Sampling Date": "",
  },
  {
    Batch: "2",
    "L1 Analyst - ECM": "Smruti Panda",
    "L1 Analyst": "Smruti Swarupa Panda",
    "L1 QC - ECM": "Reuven Salter",
    "L1 QC": "Reuven Salter",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Kiran Goli",
    "L2 QC": "Michael Herpin",
    "L2 Team Lead": "Michael Herpin",
    "Case Type": "Location Based",
    Location: "Hyderabad",
    "Sampling Date": "",
  },
  {
    Batch: "2",
    "L1 Analyst - ECM": "Subham Agarwal",
    "L1 Analyst": "Subham Agarwal",
    "L1 QC - ECM": "Rajat Lamba",
    "L1 QC": "Rajat Lamba",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Wendy Arroyo",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Gurgaon",
    "Sampling Date": "",
  },
  {
    Batch: "3 - S",
    "L1 Analyst - ECM": "Angad Singh",
    "L1 Analyst": "Angad Singh",
    "L1 QC - ECM": "Vivek Chharia",
    "L1 QC": "Vivek Chharia",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Kiran Goli",
    "L2 QC": "Michael Herpin",
    "L2 Team Lead": "Michael Herpin",
    "Case Type": "Location Based",
    Location: "Hyderabad",
    "Sampling Date": "",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Aniket Dey",
    "L1 Analyst": "Aniket Dey",
    "L1 QC - ECM": "Hafiza Ansari",
    "L1 QC": "Hafiza Ansari",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Kiran Goli",
    "L2 QC": "Kassidy Collins",
    "L2 Team Lead": "Michael Herpin",
    "Case Type": "Location Based",
    Location: "Hyderabad",
    "Sampling Date": "",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Anshika Tripathi",
    "L1 Analyst": "Anshika Tripathi",
    "L1 QC - ECM": "Vivek Chharia",
    "L1 QC": "Vivek Chharia",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Kiran Goli",
    "L2 QC": "Kassidy Collins",
    "L2 Team Lead": "Michael Herpin",
    "Case Type": "Location Based",
    Location: "Hyderabad",
    "Sampling Date": "",
  },
  {
    Batch: "3 - S",
    "L1 Analyst - ECM": "Bhavya Gupta",
    "L1 Analyst": "Bhavya Gupta",
    "L1 QC - ECM": "Ashwathy Nair",
    "L1 QC": "Ashwathy Biju Nair",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Amanda Gerwel",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Gurgaon",
    "Sampling Date": "",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Bhavya Ranka",
    "L1 Analyst": "Bhavya Ranka",
    "L1 QC - ECM": "Ashwathy Nair",
    "L1 QC": "Ashwathy Biju Nair",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Amanda Gerwel",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Gurgaon",
    "Sampling Date": "",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Chaturvedi Anmol",
    "L1 Analyst": "Chaturvedi Anmol",
    "L1 QC - ECM": "Rajeev Ratna",
    "L1 QC": "Rajeev Ratna",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Amanda Gerwel",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Gurgaon",
    "Sampling Date": "",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Devanshu Bhalla",
    "L1 Analyst": "Devanshu Bhalla",
    "L1 QC - ECM": "Vivek Chharia",
    "L1 QC": "Vivek Chharia",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Kiran Goli",
    "L2 QC": "Michael Herpin",
    "L2 Team Lead": "Michael Herpin",
    "Case Type": "Location Based",
    Location: "Hyderabad",
    "Sampling Date": "",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Faizan Aman",
    "L1 Analyst": "Faizan Aman",
    "L1 QC - ECM": "Rajeev Ratna",
    "L1 QC": "Rajeev Ratna",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Amanda Gerwel",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Gurgaon",
    "Sampling Date": "",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Gurudutt Pal",
    "L1 Analyst": "Gurudutt Pal",
    "L1 QC - ECM": "Rajeev Ratna",
    "L1 QC": "Rajeev Ratna",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Amanda Gerwel",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Gurgaon",
    "Sampling Date": "",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Faizan Aman",
    "L1 Analyst": "Faizan Aman",
    "L1 QC - ECM": "Rajeev Ratna",
    "L1 QC": "Rajeev Ratna",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Amanda Gerwel",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Gurgaon",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Gurudutt Pal",
    "L1 Analyst": "Gurudutt Pal",
    "L1 QC - ECM": "Rajeev Ratna",
    "L1 QC": "Rajeev Ratna",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Amanda Gerwel",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Gurgaon",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Ishdeep Bharg",
    "L1 Analyst": "Akash Kumar Ojha",
    "L1 QC - ECM": "Hafiza Ansari",
    "L1 QC": "Hafiza Ansari",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Goli",
    "L2 QC": "Kassidy Collins",
    "L2 Team Lead": "Michael Herpin",
    "Case Type": "Location Based",
    Location: "Hyderabad",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Jassal Chhavi",
    "L1 Analyst": "Jassal Chhavi",
    "L1 QC - ECM": "Hiteshwar Dutt",
    "L1 QC": "Hiteshwar Dutt",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Goli",
    "L2 QC": "Amanda Gerwel",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Gurgaon",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Manasvi Sanwal",
    "L1 Analyst": "Manasvi Sanwal",
    "L1 QC - ECM": "Hiteshwar Dutt",
    "L1 QC": "Hiteshwar Dutt",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Goli",
    "L2 QC": "Amanda Gerwel",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Gurgaon",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Muskan LNU",
    "L1 Analyst": "Muskan LNU",
    "L1 QC - ECM": "Reuven Salter",
    "L1 QC": "Reuven Salter",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Amanda Gerwel",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Hyderabad",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Naincy LNU",
    "L1 Analyst": "Naincy LNU",
    "L1 QC - ECM": "Vivek Chharia",
    "L1 QC": "Vivek Chharia",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Goli",
    "L2 QC": "Wendy Arroyo",
    "L2 Team Lead": "Michael Herpin",
    "Case Type": "Location Based",
    Location: "Hyderabad",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Nandini Sarda",
    "L1 Analyst": "Nandini Sarda",
    "L1 QC - ECM": "Vivek Chharia",
    "L1 QC": "Vivek Chharia",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Goli",
    "L2 QC": "Wendy Arroyo",
    "L2 Team Lead": "Michael Herpin",
    "Case Type": "Location Based",
    Location: "Hyderabad",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Neha Rajeevan",
    "L1 Analyst": "Neha Rajeevan",
    "L1 QC - ECM": "Abhinav Khatri",
    "L1 QC": "Abhinav Khatri",
    "L1 Team Lead - ECM": "Valloor Harisankar",
    "L1 Team Lead": "Harisankar, V M",
    "L2 QC": "Michael Herpin",
    "L2 Team Lead": "Michael Herpin",
    "Case Type": "Location Based",
    Location: "Gurgaon",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Nerella Bindu",
    "L1 Analyst": "Nerella Hema Bindu",
    "L1 QC - ECM": "Vivek Chharia",
    "L1 QC": "Vivek Chharia",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Goli",
    "L2 QC": "Michael Herpin",
    "L2 Team Lead": "Michael Herpin",
    "Case Type": "Sampling - Location Based",
    Location: "Hyderabad",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Noshi Sandhya",
    "L1 Analyst": "Noshi Babu Sandhya",
    "L1 QC - ECM": "Reuven Salter",
    "L1 QC": "Reuven Salter",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Amanda Gerwel",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Gurgaon",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Parina Ahluwalia",
    "L1 Analyst": "Parina Ahluwalia",
    "L1 QC - ECM": "Ajay Minocha",
    "L1 QC": "Ajay Minocha",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Amanda Gerwel",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Sampling - Location Based",
    Location: "Gurgaon",
  },
  {
    Batch: "3 - S",
    "L1 Analyst - ECM": "Rishabh Yadav",
    "L1 Analyst": "Rishabh Yadav",
    "L1 QC - ECM": "Ashwathy Biju Nair",
    "L1 QC": "Ashwathy Biju Nair",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Amanda Gerwel",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Hyderabad",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Riya LNU",
    "L1 Analyst": "Riya LNU",
    "L1 QC - ECM": "Valloor Harisankar",
    "L1 QC": "Harisankar, V M",
    "L1 Team Lead - ECM": "Valloor Harisankar",
    "L1 Team Lead": "Harisankar, V M",
    "L2 QC": "Chantell Redish",
    "L2 Team Lead": "Katie Fogle",
    "Case Type": "Location Based",
    Location: "Bangalore",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Roshni Shrestha",
    "L1 Analyst": "Roshni Shrestha",
    "L1 QC - ECM": "Hafiza Ansari",
    "L1 QC": "Hafiza Ansari",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Amanda Gerwel",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Gurgaon",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Sai Anasuri",
    "L1 Analyst": "Sai Krishna Anasuri",
    "L1 QC - ECM": "Abhinav Khatri",
    "L1 QC": "Abhinav Khatri",
    "L1 Team Lead - ECM": "Valloor Harisankar",
    "L1 Team Lead": "Harisankar, V M",
    "L2 QC": "Chantell Redish",
    "L2 Team Lead": "Katie Fogle",
    "Case Type": "Location Based",
    Location: "Bangalore",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Sameer Gupta",
    "L1 Analyst": "Sameer Gupta",
    "L1 QC - ECM": "Reuven Salter",
    "L1 QC": "Reuven Salter",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Goli",
    "L2 QC": "Kassidy Collins",
    "L2 Team Lead": "Michael Herpin",
    "Case Type": "Location Based",
    Location: "Hyderabad",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Sumit Rajawat",
    "L1 Analyst": "Sumit Rajawat",
    "L1 QC - ECM": "Anuloma Tripathy",
    "L1 QC": "Anuloma Tripathy",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Amanda Gerwel",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Gurgaon",
  },
  {
    Batch: "3",
    "L1 Analyst - ECM": "Sweta Kumari",
    "L1 Analyst": "Sweta Kumari",
    "L1 QC - ECM": "Rajeev Ratna",
    "L1 QC": "Rajeev Ratna",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Amanda Gerwel",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Gurgaon",
  },
  {
    Batch: "3 - S",
    "L1 Analyst - ECM": "Vivek Patel",
    "L1 Analyst": "Vivek Singh Patel",
    "L1 QC - ECM": "Reuven Salter",
    "L1 QC": "Reuven Salter",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Goli",
    "L2 QC": "Kassidy Collins",
    "L2 Team Lead": "Michael Herpin",
    "Case Type": "Location Based",
    Location: "Hyderabad",
  },
  {
    Batch: "4",
    "L1 Analyst - ECM": "Erikhomba Huidrom",
    "L1 Analyst": "Erikhomba Meetei Huidrom",
    "L1 QC - ECM": "Santhosh Somasundaram",
    "L1 QC": "Santhosh Somasundaram",
    "L1 Team Lead - ECM": "Valloor Harisankar",
    "L1 Team Lead": "Harisankar, V M",
    "L2 QC": "Sai Goli",
    "L2 Team Lead": "Sai Kiran Goli",
    "Case Type": "Location Based",
    Location: "Bangalore",
  },
  {
    Batch: "4",
    "L1 Analyst - ECM": "Hezron Parado",
    "L1 Analyst": "Hezron Parado",
    "L1 QC - ECM": "Hiteshwar Dutt",
    "L1 QC": "Hiteshwar Dutt",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Goli",
    "L2 QC": "Sai Kiran Goli",
    "L2 Team Lead": "Katie Fogle",
    "Case Type": "Location Based",
    Location: "Bangalore",
  },
  {
    Batch: "4",
    "L1 Analyst - ECM": "Maahi Agarwal",
    "L1 Analyst": "Maahi Agarwal",
    "L1 QC - ECM": "Reuven Salter",
    "L1 QC": "Reuven Salter",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Goli",
    "L2 QC": "Sai Kiran Goli",
    "L2 Team Lead": "Katie Fogle",
    "Case Type": "Location Based",
    Location: "Bangalore",
  },
  {
    Batch: "4",
    "L1 Analyst - ECM": "Madhur Grover",
    "L1 Analyst": "Madhur Grover",
    "L1 QC - ECM": "Reuven Salter",
    "L1 QC": "Reuven Salter",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Goli",
    "L2 QC": "Sai Kiran Goli",
    "L2 Team Lead": "Katie Fogle",
    "Case Type": "Sampling - Location Based",
    Location: "Hyderabad",
  },
  {
    Batch: "4",
    "L1 Analyst - ECM": "Meenakshi Jagadeep",
    "L1 Analyst": "Meenakshi Vailailip Jagadeep",
    "L1 QC - ECM": "Hafiza Ansari",
    "L1 QC": "Hafiza Ansari",
    "L1 Team Lead - ECM": "Ajay Minocha",
    "L1 Team Lead": "Ajay Minocha",
    "L2 QC": "Amanda Gerwel",
    "L2 Team Lead": "Amanda Gerwel",
    "Case Type": "Location Based",
    Location: "Gurgaon",
  },
  {
    Batch: "4",
    "L1 Analyst - ECM": "Nandini Prakash",
    "L1 Analyst": "Nandini Prakash",
    "L1 QC - ECM": "Rajeev Ratna",
    "L1 QC": "Rajeev Ratna",
    "L1 Team Lead - ECM": "Valloor Harisankar",
    "L1 Team Lead": "Harisankar, V M",
    "L2 QC": "Kassidy Collins",
    "L2 Team Lead": "Michael Herpin",
    "Case Type": "Location Based",
    Location: "Hyderabad",
  },
  {
    Batch: "5",
    "L1 Analyst - ECM": "No ECM",
    "L1 Analyst": "Alicia Argoya Swamy",
    "L1 QC - ECM": "Valloor Harisankar",
    "L1 QC": "Harisankar, V M",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Goli",
    "L2 QC": "Kassidy Collins",
    "L2 Team Lead": "Michael Herpin",
    "Case Type": "Location Based",
    Location: "Hyderabad",
  },
  {
    Batch: "5",
    "L1 Analyst - ECM": "Sarthak Mohanty",
    "L1 Analyst": "Sarthak Mohanty",
    "L1 QC - ECM": "Hafiza Ansari",
    "L1 QC": "Hafiza Ansari",
    "L1 Team Lead - ECM": "Sai Goli",
    "L1 Team Lead": "Sai Goli",
    "L2 QC": "Kassidy Collins",
    "L2 Team Lead": "Michael Herpin",
    "Case Type": "Location Based",
    Location: "Hyderabad",
  },
];
const routes = [
  {
    name: "Teams",
    content: "Analyst List",
    description: "List of all analyst working on cases",
    slug: "Teams",
  },
  {
    name: "Tools",
    content: "Tools Content",
    description: "List of all analyst working on cases",
    slug: "Tools",
  },
  {
    name: "Operations",
    content: "Operations Content",
    description: "List of all analyst working on cases",
    slug: "Operations",
  },
  {
    name: "Research",
    content: "Research Content",
    description: "List of all analyst working on cases",
    slug: "Research",
  },
  {
    name: "Documents",
    content: "Documents Content",
    description: "List of all analyst working on cases",
    slug: "Documents",
  },
  {
    name: "Narations",
    content: "Narations Content",
    description: "List of all analyst working on cases",
    slug: "Narations",
  },
];
const dueDiligenceLinks = {
  individuals: [
    {
      "Site Name": "True People Search",
      Website: "https://www.truepeoplesearch.com/",
    },
    {
      "Site Name": "Fast People Search",
      Website: "https://www.fastpeoplesearch.com/",
    },
    {
      "Site Name": "OFAC",
      Website: "https://sanctionssearch.ofac.treas.gov/",
    },
    { "Site Name": "Radaris", Website: "https://radaris.com/" },
    { "Site Name": "My Life", Website: "https://www.mylife.com/" },
    {
      "Site Name": "Cyber Background Checks",
      Website: "https://www.cyberbackgroundchecks.com/",
    },
    { "Site Name": "White Pages", Website: "https://www.whitepages.com/" },
    { "Site Name": "LinkedIn", Website: "https://www.linkedin.com/" },
    { "Site Name": "Facebook", Website: "https://www.facebook.com/" },
    { "Site Name": "Instagram", Website: "https://www.instagram.com/" },
    { "Site Name": "Zoom Info", Website: "https://www.zoominfo.com/" },

    { "Site Name": "Spokeo", Website: "https://www.spokeo.com/" },
    { "Site Name": "Venmo", Website: "https://www.venmo.com/" },
  ],
  businesses: [
    { "Site Name": "Bizapedia", Website: "https://www.bizapedia.com/" },
    {
      "Site Name": "Open Corporates",
      Website: "https://opencorporates.com/",
    },
    {
      "Site Name": "Forbes",
      Website: "https://www.forbes.com/advisor/business/free-ein-lookup/",
    },
    {
      "Site Name": "Better Business Bureau",
      Website: "https://www.bbb.org/",
    },
    { "Site Name": "Manta", Website: "https://www.manta.com/" },
    { "Site Name": "IRS", Website: "https://apps.irs.gov/app/eos/" },
    { "Site Name": "Dun and Bradstreet", Website: "https://www.dnb.com/" },
    { "Site Name": "Bloomberg", Website: "https://www.bloomberg.com/" },
    { "Site Name": "Archive.org", Website: "https://archive.org/" },
    { "Site Name": "Yahoo Finance", Website: "https://finance.yahoo.com/" },
  ],
  nonprofits: [
    { "Site Name": "Guidestar", Website: "https://www.guidestar.org/" },
    { "Site Name": "Charity Check", Website: "https://charitycheck101.org/" },
    {
      "Site Name": "Charity Watch",
      Website: "https://www.charitywatch.org/",
    },
    { "Site Name": "ICIJ", Website: "https://offshoreleaks.icij.org/" },
  ],
};
